input {
  syslog {
    port => 5001
    type => "syslog_plain"
  }
  syslog {
    port => 5002
    type => "syslog_json"
  }
}

filter {
  if [type] == "syslog_json" {
    json {
      source => "message"
    }
    mutate {
      add_field => { "environment" => "docker" }
      remove_field => [ "message" ]
    }
    if [timestamp] {
      date {
        match => [ "timestamp", "ISO8601" ]
        target => "@timestamp"
      }
    }
  }
  if [type] == "syslog_plain" {
    grok {
      match => {
        "message" => "%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:log_level}\s+%{GREEDYDATA:log_message}"
      }
      tag_on_failure => ["_grokparsefailure_simple"]
    }
    date {
      match => ["timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS Z"]
      target => "@timestamp"
    }
    mutate {
      add_field => {
        "service" => "%{tag}"
        "environment" => "docker"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
}
